### ISSUE TITLE
give mpenkov write access to master

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/bounter#46]
@piskvorky I'm unable to push to master. I think I may not have the right permissions for this repo.

**Comment by piskvorky** [comment]
Done.

**Comment by mpenkov** [comment]
I'm still unable to push. From what I can tell in the UI, I'm still only a collaborator for bounter.

![Screen Shot 2020-08-16 at 21 34 44](https://user-images.githubusercontent.com/1101396/90334392-4f1ecc00-e008-11ea-911b-ccbd44043421.png)

**Comment by piskvorky** [comment]
This is what I see. There's no higher privilege than `admin`:

<img width="1440" alt="Screen Shot 2020-08-16 at 15 56 42" src="https://user-images.githubusercontent.com/610412/90335992-23382200-dfd9-11ea-8834-9d30424b129e.png">

**Comment by mpenkov** [comment]
Alright, I'll take it up with github support
